# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55ca3ea4b07f5dbc75842438b6caf3d9dc559a57b59950c5eb1682f640fde7408d540dc81164613383563631883d25b1e40568f071fca697d228f91575e00288

test:
  secret_key_base: 35c35601a8d451cca3e21b4dc934e30f9d6e607ca9ec6b32e74138eb03917ba2681d95c2e5bc0b53f7875881f3ea93f287626259d10da59973ee34e0997eb909

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
